// Code generated by "stringer -type=Algorithm -output algo_s.go"; DO NOT EDIT.

package yubihsm2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RsaPkcs1Sha1-1]
	_ = x[RsaPkcs1Sha256-2]
	_ = x[RsaPkcs1Sha384-3]
	_ = x[RsaPkcs1Sha512-4]
	_ = x[RsaPssSha1-5]
	_ = x[RsaPssSha256-6]
	_ = x[RsaPssSha384-7]
	_ = x[RsaPssSha512-8]
	_ = x[Rsa2048-9]
	_ = x[Rsa3072-10]
	_ = x[Rsa4096-11]
	_ = x[Secp256r1-12]
	_ = x[Secp384r1-13]
	_ = x[Secp521r1-14]
	_ = x[Secp256k1-15]
	_ = x[Brainpool256r1-16]
	_ = x[Brainpool384r1-17]
	_ = x[Brainpool512r1-18]
	_ = x[HmacSha1-19]
	_ = x[HmacSha256-20]
	_ = x[HmacSha384-21]
	_ = x[HmacSha512-22]
	_ = x[EcdsaSha1-23]
	_ = x[Ecdh-24]
	_ = x[RsaOaepSha1-25]
	_ = x[RsaOaepSha256-26]
	_ = x[RsaOaepSha384-27]
	_ = x[RsaOaepSha512-28]
	_ = x[Aes128CcmWrap-29]
	_ = x[OpaqueData-30]
	_ = x[OpaqueX509Cert-31]
	_ = x[Mgf1Sha1-32]
	_ = x[Mgf1Sha256-33]
	_ = x[Mgf1Sha384-34]
	_ = x[Mgf1Sha512-35]
	_ = x[SshTemplate-36]
	_ = x[YubicoOtpAes128-37]
	_ = x[YubicoAesAuth-38]
	_ = x[YubicoOtpAes192-39]
	_ = x[YubicoOtpAes256-40]
	_ = x[Aes192CcmWrap-41]
	_ = x[Aes256CcmWrap-42]
	_ = x[EcdsaSha256-43]
	_ = x[EcdsaSha384-44]
	_ = x[EcdsaSha512-45]
	_ = x[AlgorighmED25519-46]
	_ = x[Secp224r1-47]
}

const _Algorithm_name = "RsaPkcs1Sha1RsaPkcs1Sha256RsaPkcs1Sha384RsaPkcs1Sha512RsaPssSha1RsaPssSha256RsaPssSha384RsaPssSha512Rsa2048Rsa3072Rsa4096Secp256r1Secp384r1Secp521r1Secp256k1Brainpool256r1Brainpool384r1Brainpool512r1HmacSha1HmacSha256HmacSha384HmacSha512EcdsaSha1EcdhRsaOaepSha1RsaOaepSha256RsaOaepSha384RsaOaepSha512Aes128CcmWrapOpaqueDataOpaqueX509CertMgf1Sha1Mgf1Sha256Mgf1Sha384Mgf1Sha512SshTemplateYubicoOtpAes128YubicoAesAuthYubicoOtpAes192YubicoOtpAes256Aes192CcmWrapAes256CcmWrapEcdsaSha256EcdsaSha384EcdsaSha512AlgorighmED25519Secp224r1"

var _Algorithm_index = [...]uint16{0, 12, 26, 40, 54, 64, 76, 88, 100, 107, 114, 121, 130, 139, 148, 157, 171, 185, 199, 207, 217, 227, 237, 246, 250, 261, 274, 287, 300, 313, 323, 337, 345, 355, 365, 375, 386, 401, 414, 429, 444, 457, 470, 481, 492, 503, 519, 528}

func (i Algorithm) String() string {
	i -= 1
	if i >= Algorithm(len(_Algorithm_index)-1) {
		return "Algorithm(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Algorithm_name[_Algorithm_index[i]:_Algorithm_index[i+1]]
}
